// ============================================
// Plans Data — Catálogo default SaaS
// Fuente de verdad para features, límites y planes semilla.
// NOTA: este archivo se puede override en runtime via store.setSetting('plans_catalog')
// Cualquier admin edita el catálogo desde /admin/planes sin tocar este archivo.
// ============================================

// ---------- Categorías de funcionalidades ----------
// Cada categoría agrupa límites relacionados. Se mostrarán como tabs en el admin
// y como secciones en la página de pricing para el usuario final.
export const FEATURE_CATEGORIES = {
  cuentas: {
    id: 'cuentas',
    name: 'Cuentas',
    icon: 'wallet',
    description: 'Cuentas bancarias, efectivo y billeteras digitales',
    limits: [
      { key: 'max_accounts', label: 'Cuentas activas', unit: 'cuentas', default_free: 2, default_unlimited: -1 },
    ],
  },
  tarjetas: {
    id: 'tarjetas',
    name: 'Tarjetas',
    icon: 'creditCard',
    description: 'Tarjetas de crédito propias y externas',
    limits: [
      { key: 'max_cards', label: 'Tarjetas propias', unit: 'tarjetas', default_free: 1, default_unlimited: -1 },
      { key: 'max_external_cards', label: 'Tarjetas externas', unit: 'tarjetas', default_free: 0, default_unlimited: -1 },
    ],
  },
  transacciones: {
    id: 'transacciones',
    name: 'Transacciones',
    icon: 'transaction',
    description: 'Ingresos, gastos y transferencias',
    limits: [
      { key: 'max_transactions_month', label: 'Transacciones por mes', unit: 'tx/mes', default_free: 50, default_unlimited: -1 },
      { key: 'max_templates', label: 'Plantillas', unit: 'plantillas', default_free: 3, default_unlimited: -1 },
    ],
  },
  deudas: {
    id: 'deudas',
    name: 'Deudas',
    icon: 'handCoins',
    description: 'Deudas activas, préstamos, cuentas por cobrar/pagar',
    limits: [
      { key: 'max_debts', label: 'Deudas activas', unit: 'deudas', default_free: 3, default_unlimited: -1 },
      { key: 'max_loans', label: 'Préstamos activos', unit: 'préstamos', default_free: 2, default_unlimited: -1 },
      { key: 'max_receivables', label: 'Cuentas por cobrar', unit: 'items', default_free: 5, default_unlimited: -1 },
      { key: 'max_payables', label: 'Cuentas por pagar', unit: 'items', default_free: 5, default_unlimited: -1 },
    ],
  },
  clientes: {
    id: 'clientes',
    name: 'Clientes / Terceros',
    icon: 'user',
    description: 'Contactos, clientes y terceros',
    limits: [
      { key: 'max_clients', label: 'Clientes / Terceros', unit: 'contactos', default_free: 10, default_unlimited: -1 },
    ],
  },
  metas: {
    id: 'metas',
    name: 'Metas',
    icon: 'goal',
    description: 'Objetivos de ahorro',
    limits: [
      { key: 'max_goals', label: 'Metas activas', unit: 'metas', default_free: 2, default_unlimited: -1 },
    ],
  },
  suscripciones: {
    id: 'suscripciones',
    name: 'Suscripciones',
    icon: 'subscription',
    description: 'Pagos recurrentes',
    limits: [
      { key: 'max_subscriptions', label: 'Suscripciones', unit: 'subs', default_free: 3, default_unlimited: -1 },
    ],
  },
  ia: {
    id: 'ia',
    name: 'Inteligencia Artificial',
    icon: 'star',
    description: 'Asistente conversacional y automatizaciones',
    features: ['ai_chat', 'ai_categorization', 'ai_insights'],
    limits: [
      { key: 'max_ai_queries_month', label: 'Consultas IA por mes', unit: 'queries/mes', default_free: 10, default_unlimited: -1 },
    ],
  },
  reportes: {
    id: 'reportes',
    name: 'Reportes & Analytics',
    icon: 'barChart',
    description: 'Reportes avanzados y exports',
    features: ['advanced_reports', 'custom_dashboards', 'historical_analytics'],
    limits: [],
  },
  exportacion: {
    id: 'exportacion',
    name: 'Exportación / Importación',
    icon: 'arrowUp',
    description: 'Exportar y restaurar data',
    features: ['export_pdf', 'export_excel', 'import_csv', 'auto_backup'],
    limits: [
      { key: 'max_exports_month', label: 'Exportaciones por mes', unit: 'exports/mes', default_free: 3, default_unlimited: -1 },
    ],
  },
  usuarios: {
    id: 'usuarios',
    name: 'Usuarios & Workspaces',
    icon: 'user',
    description: 'Multiusuario y espacios de trabajo',
    limits: [
      { key: 'max_users', label: 'Usuarios del workspace', unit: 'usuarios', default_free: 1, default_unlimited: -1 },
      { key: 'max_workspaces', label: 'Workspaces', unit: 'ws', default_free: 1, default_unlimited: -1 },
    ],
  },
  integraciones: {
    id: 'integraciones',
    name: 'Integraciones',
    icon: 'bank',
    description: 'Conexiones con bancos, APIs y servicios externos',
    features: ['bank_sync', 'webhooks', 'api_access', 'zapier'],
    limits: [],
  },
};

// ---------- Todas las feature flags disponibles ----------
export const ALL_FEATURES = [
  // IA
  'ai_chat',
  'ai_categorization',
  'ai_insights',
  // Reportes
  'advanced_reports',
  'custom_dashboards',
  'historical_analytics',
  // Exportación
  'export_pdf',
  'export_excel',
  'import_csv',
  'auto_backup',
  // Integraciones
  'bank_sync',
  'webhooks',
  'api_access',
  'zapier',
  // Customización
  'custom_categories_unlimited',
  'custom_themes',
  'white_label',
  // Soporte
  'priority_support',
  'dedicated_manager',
];

// ---------- Planes semilla ----------
// -1 significa ilimitado en cualquier límite numérico.
// Los planes creados por el admin sobrescribirán estos en store.setSetting('plans_catalog')
export const DEFAULT_PLANS = [
  {
    id: 'plan_free',
    name: 'Free',
    description: 'Empieza gratis y controla tus finanzas básicas.',
    price: 0,
    currency: 'USD',
    billing: 'monthly', // monthly | annual | once
    status: 'active',
    featured: false,
    order: 1,
    color: '#A1A1AA',
    limits: {
      max_accounts: 2,
      max_cards: 1,
      max_external_cards: 0,
      max_transactions_month: 50,
      max_templates: 3,
      max_debts: 3,
      max_loans: 2,
      max_receivables: 5,
      max_payables: 5,
      max_clients: 10,
      max_goals: 2,
      max_subscriptions: 3,
      max_ai_queries_month: 10,
      max_exports_month: 3,
      max_users: 1,
      max_workspaces: 1,
    },
    features: {
      ai_chat: true,
      ai_categorization: false,
      ai_insights: false,
      advanced_reports: false,
      custom_dashboards: false,
      historical_analytics: false,
      export_pdf: true,
      export_excel: false,
      import_csv: false,
      auto_backup: false,
      bank_sync: false,
      webhooks: false,
      api_access: false,
      zapier: false,
      custom_categories_unlimited: false,
      custom_themes: true,
      white_label: false,
      priority_support: false,
      dedicated_manager: false,
    },
    tagline: 'Para empezar',
    cta: 'Plan actual',
  },
  {
    id: 'plan_starter',
    name: 'Starter',
    description: 'Organiza tus finanzas personales con más capacidad.',
    price: 4.99,
    currency: 'USD',
    billing: 'monthly',
    status: 'active',
    featured: false,
    order: 2,
    color: '#4F46E5',
    limits: {
      max_accounts: 5,
      max_cards: 3,
      max_external_cards: 3,
      max_transactions_month: 500,
      max_templates: 10,
      max_debts: 10,
      max_loans: 5,
      max_receivables: 20,
      max_payables: 20,
      max_clients: 50,
      max_goals: 5,
      max_subscriptions: 10,
      max_ai_queries_month: 100,
      max_exports_month: 10,
      max_users: 1,
      max_workspaces: 1,
    },
    features: {
      ai_chat: true,
      ai_categorization: true,
      ai_insights: false,
      advanced_reports: true,
      custom_dashboards: false,
      historical_analytics: false,
      export_pdf: true,
      export_excel: true,
      import_csv: true,
      auto_backup: false,
      bank_sync: false,
      webhooks: false,
      api_access: false,
      zapier: false,
      custom_categories_unlimited: true,
      custom_themes: true,
      white_label: false,
      priority_support: false,
      dedicated_manager: false,
    },
    tagline: 'Popular',
    cta: 'Actualizar a Starter',
  },
  {
    id: 'plan_pro',
    name: 'Pro',
    description: 'Todo lo que necesitas para gestionar tus finanzas como un profesional.',
    price: 14.99,
    currency: 'USD',
    billing: 'monthly',
    status: 'active',
    featured: true,
    order: 3,
    color: '#8B5CF6',
    limits: {
      max_accounts: -1,
      max_cards: -1,
      max_external_cards: -1,
      max_transactions_month: -1,
      max_templates: -1,
      max_debts: -1,
      max_loans: -1,
      max_receivables: -1,
      max_payables: -1,
      max_clients: -1,
      max_goals: -1,
      max_subscriptions: -1,
      max_ai_queries_month: 1000,
      max_exports_month: -1,
      max_users: 3,
      max_workspaces: 3,
    },
    features: {
      ai_chat: true,
      ai_categorization: true,
      ai_insights: true,
      advanced_reports: true,
      custom_dashboards: true,
      historical_analytics: true,
      export_pdf: true,
      export_excel: true,
      import_csv: true,
      auto_backup: true,
      bank_sync: false,
      webhooks: true,
      api_access: false,
      zapier: true,
      custom_categories_unlimited: true,
      custom_themes: true,
      white_label: false,
      priority_support: true,
      dedicated_manager: false,
    },
    tagline: 'Más elegido',
    cta: 'Actualizar a Pro',
  },
  {
    id: 'plan_business',
    name: 'Business',
    description: 'Para equipos, empresas y usuarios intensivos. Todo ilimitado + integraciones.',
    price: 39.99,
    currency: 'USD',
    billing: 'monthly',
    status: 'active',
    featured: false,
    order: 4,
    color: '#EC4899',
    limits: {
      max_accounts: -1,
      max_cards: -1,
      max_external_cards: -1,
      max_transactions_month: -1,
      max_templates: -1,
      max_debts: -1,
      max_loans: -1,
      max_receivables: -1,
      max_payables: -1,
      max_clients: -1,
      max_goals: -1,
      max_subscriptions: -1,
      max_ai_queries_month: -1,
      max_exports_month: -1,
      max_users: -1,
      max_workspaces: -1,
    },
    features: {
      ai_chat: true,
      ai_categorization: true,
      ai_insights: true,
      advanced_reports: true,
      custom_dashboards: true,
      historical_analytics: true,
      export_pdf: true,
      export_excel: true,
      import_csv: true,
      auto_backup: true,
      bank_sync: true,
      webhooks: true,
      api_access: true,
      zapier: true,
      custom_categories_unlimited: true,
      custom_themes: true,
      white_label: true,
      priority_support: true,
      dedicated_manager: true,
    },
    tagline: 'Elite',
    cta: 'Actualizar a Business',
  },
];

// ---------- Plan "ghost" — usado como fallback si el usuario no tiene plan asignado ----------
// Es PERMISIVO: no bloquea nada. Esto garantiza compatibilidad total con usuarios
// que ya existen antes de activar el sistema de planes.
export const LEGACY_UNLIMITED_PLAN = {
  id: 'plan_legacy_unlimited',
  name: 'Legacy',
  description: 'Plan heredado con acceso completo (compatibilidad retroactiva).',
  price: 0,
  currency: 'USD',
  billing: 'once',
  status: 'active',
  hidden: true,
  limits: Object.fromEntries(
    Object.values(FEATURE_CATEGORIES).flatMap(cat => (cat.limits || []).map(l => [l.key, -1]))
  ),
  features: Object.fromEntries(ALL_FEATURES.map(f => [f, true])),
};
